<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>CrossBusExplorer.Host</RootNamespace>
        <AssemblyName>CrossBusExplorer.Host</AssemblyName>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(RunConfiguration)' == 'CrossBusExplorer' " />
    <ItemGroup>
      <Content Remove="appsettings.Development.json" />
      <Compile Remove="Mutations\**\*.cs" />
      <Compile Remove="Queries\**\*.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Management\Management.csproj" />
      <ProjectReference Include="..\..\Core\ServiceBus\ServiceBus.csproj" />
    </ItemGroup>

</Project>
