import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRightLeft, Copy, Filter, Layers3, MessageSquareText, RefreshCw, Save, ShieldAlert, Trash2 } from "lucide-react";
import { api } from "../api";
import type { Rule, SubscriptionDetails } from "../types";
import { Capability, Metric } from "./QueueOverview";
import { MessagesWorkspace } from "./MessagesWorkspace";

export function SubscriptionOverview({ connectionName, topicName, subscriptionName, onDeleted, onJobStarted }: { connectionName: string; topicName: string; subscriptionName: string; onDeleted: () => void; onJobStarted: () => void }) {
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<"overview" | "messages" | "rules" | "settings">("overview");
  const subscription = useQuery({ queryKey: ["subscription", connectionName, topicName, subscriptionName], queryFn: () => api.subscription(connectionName, topicName, subscriptionName) });
  const clone = useMutation({ mutationFn: (name: string) => api.cloneSubscription(connectionName, topicName, subscriptionName, name), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["subscriptions", connectionName, topicName] }) });
  const remove = useMutation({ mutationFn: () => api.deleteSubscription(connectionName, topicName, subscriptionName), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["subscriptions", connectionName, topicName] }); onDeleted(); } });

  if (subscription.isPending) return <State title="Loading subscription" detail="Reading settings and runtime metrics…" />;
  if (subscription.error) return <State title="Unable to load subscription" detail={subscription.error.message} error />;
  const details = subscription.data;
  const error = clone.error ?? remove.error;

  return <div className="content-page wide-page">
    <header className="page-header"><div><div className="breadcrumbs">{connectionName} / Topics / {topicName} / {subscriptionName}</div><div className="title-line"><div className="resource-icon subscription"><Layers3 size={22} /></div><div><div className="title-with-status"><h1>{subscriptionName}</h1><span className={`status ${details.info.status.toLowerCase()}`}>{details.info.status}</span></div><p>Subscription messages, filters, and delivery behavior</p></div></div></div><div className="header-actions"><button className="button secondary" onClick={() => { const name = window.prompt("Name for the cloned subscription", `${subscriptionName}-copy`)?.trim(); if (name) clone.mutate(name); }}><Copy size={15} /> Clone</button><button className="button secondary" onClick={() => subscription.refetch()}><RefreshCw size={15} /> Refresh</button><button className="button danger-ghost" onClick={() => window.confirm(`Delete subscription ${subscriptionName}?`) && remove.mutate()}><Trash2 size={15} /> Delete</button></div></header>
    {error && <div className="notice error">{error.message}</div>}
    <div className="metric-grid compact-metrics"><Metric label="Active" value={details.info.activeMessagesCount} icon={<MessageSquareText />} tone="accent" /><Metric label="Dead letter" value={details.info.deadLetterMessagesCount} icon={<ShieldAlert />} tone={details.info.deadLetterMessagesCount ? "danger" : "neutral"} /><Metric label="Transfer" value={details.info.transferMessagesCount} icon={<ArrowRightLeft />} tone="neutral" /></div>
    <div className="tab-strip"><Tab active={tab === "overview"} onClick={() => setTab("overview")}>Overview</Tab><Tab active={tab === "messages"} onClick={() => setTab("messages")}>Messages <span>{(details.info.activeMessagesCount + details.info.deadLetterMessagesCount).toLocaleString()}</span></Tab><Tab active={tab === "rules"} onClick={() => setTab("rules")}>Rules</Tab><Tab active={tab === "settings"} onClick={() => setTab("settings")}>Settings</Tab></div>
    {tab === "overview" && <Summary details={details} onEdit={() => setTab("settings")} />}
    {tab === "messages" && <MessagesWorkspace connectionName={connectionName} entityName={topicName} subscriptionName={subscriptionName} activeCount={details.info.activeMessagesCount} deadLetterCount={details.info.deadLetterMessagesCount} onJobStarted={onJobStarted} />}
    {tab === "rules" && <Rules connectionName={connectionName} topicName={topicName} subscriptionName={subscriptionName} />}
    {tab === "settings" && <SettingsForm connectionName={connectionName} topicName={topicName} subscriptionName={subscriptionName} details={details} />}
  </div>;
}

function Summary({ details, onEdit }: { details: SubscriptionDetails; onEdit: () => void }) {
  return <div className="overview-grid"><section className="card"><div className="card-heading"><div><span className="eyebrow">Configuration</span><h2>Delivery</h2></div><button className="button tertiary" onClick={onEdit}>Edit settings</button></div><dl className="definition-list compact"><div><dt>Max delivery count</dt><dd>{details.properties.maxDeliveryCount}</dd></div><div><dt>Lock duration</dt><dd>{details.timeSettings.lockDuration}</dd></div><div><dt>Message TTL</dt><dd>{details.timeSettings.defaultMessageTimeToLive}</dd></div><div><dt>Auto-delete on idle</dt><dd>{details.timeSettings.autoDeleteOnIdle}</dd></div><div><dt>Forward to</dt><dd>{details.properties.forwardTo || "—"}</dd></div><div><dt>Forward dead letters</dt><dd>{details.properties.forwardDeadLetteredMessagesTo || "—"}</dd></div></dl></section><section className="card"><div className="card-heading"><div><span className="eyebrow">Behavior</span><h2>Capabilities</h2></div></div><div className="capability-list"><Capability label="Sessions" enabled={details.settings.requiresSession} /><Capability label="Batched operations" enabled={details.settings.enableBatchedOperations} /><Capability label="Dead-letter expired messages" enabled={details.settings.enableDeadLetteringOnMessageExpiration} /><Capability label="Dead-letter filter errors" enabled={details.settings.enableDeadLetteringOnFilterEvaluationExceptions} /></div></section></div>;
}

function Rules({ connectionName, topicName, subscriptionName }: { connectionName: string; topicName: string; subscriptionName: string }) {
  const queryClient = useQueryClient();
  const [editing, setEditing] = useState<Rule>();
  const [originalName, setOriginalName] = useState<string>();
  const rules = useQuery({ queryKey: ["rules", connectionName, topicName, subscriptionName], queryFn: () => api.rules(connectionName, topicName, subscriptionName) });
  const save = useMutation({ mutationFn: (rule: Rule) => api.saveRule(connectionName, topicName, subscriptionName, rule, originalName), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["rules", connectionName, topicName, subscriptionName] }); setEditing(undefined); setOriginalName(undefined); } });
  const remove = useMutation({ mutationFn: (name: string) => api.deleteRule(connectionName, topicName, subscriptionName, name), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["rules", connectionName, topicName, subscriptionName] }) });
  return <section className="card table-card"><div className="card-heading"><div><span className="eyebrow">Filters</span><h2>Subscription rules</h2></div><button className="button primary" onClick={() => { setOriginalName(undefined); setEditing({ name: "", type: "Sql", value: "" }); }}><Filter size={15} /> Add rule</button></div>{rules.isPending ? <div className="empty-messages">Loading rules…</div> : rules.error ? <div className="notice error">{rules.error.message}</div> : <table className="data-table"><thead><tr><th>Actions</th><th>Name</th><th>Type</th><th>Filter value</th></tr></thead><tbody>{rules.data?.map((rule) => <tr key={rule.name}><td className="row-actions"><button onClick={() => { setOriginalName(rule.name); setEditing(rule); }}>Edit</button><button onClick={() => window.confirm(`Delete rule ${rule.name}?`) && remove.mutate(rule.name)}><Trash2 size={14} /></button></td><td>{rule.name}</td><td>{formatRuleType(rule.type)}</td><td><code>{rule.value || "—"}</code></td></tr>)}</tbody></table>}{(save.error || remove.error) && <div className="notice error">{(save.error ?? remove.error)?.message}</div>}{editing && <RuleDialog rule={editing} originalName={originalName} busy={save.isPending} onClose={() => setEditing(undefined)} onSave={(rule) => save.mutate(rule)} />}</section>;
}

function RuleDialog({ rule, originalName, busy, onClose, onSave }: { rule: Rule; originalName?: string; busy: boolean; onClose: () => void; onSave: (rule: Rule) => void }) {
  const [form, setForm] = useState(rule);
  const valueDisabled = form.type === "TrueFilter" || form.type === "FalseFilter";
  return <div className="dialog-backdrop"><div className="dialog compact-dialog"><div className="dialog-header"><div><span className="eyebrow">Rule</span><h2>{originalName ? "Edit" : "Create"} filter</h2></div></div><form onSubmit={(event) => { event.preventDefault(); onSave({ ...form, value: valueDisabled ? undefined : form.value }); }}><div className="form-grid"><label className="wide"><span>Name</span><input required disabled={!!originalName} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label className="wide"><span>Type</span><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as Rule["type"] })}><option value="TrueFilter">Always true</option><option value="FalseFilter">Always false</option><option value="Sql">SQL filter</option><option value="CorrelationId">Correlation ID</option></select></label><label className="wide"><span>Filter value</span><textarea rows={5} disabled={valueDisabled} required={!valueDisabled} value={form.value ?? ""} onChange={(event) => setForm({ ...form, value: event.target.value })} /></label></div><div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>Save rule</button></div></form></div></div>;
}

function SettingsForm({ connectionName, topicName, subscriptionName, details }: { connectionName: string; topicName: string; subscriptionName: string; details: SubscriptionDetails }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState(() => ({ topicName, subscriptionName, lockDuration: details.timeSettings.lockDuration, defaultMessageTimeToLive: details.timeSettings.defaultMessageTimeToLive, autoDeleteOnIdle: details.timeSettings.autoDeleteOnIdle, deadLetteringOnMessageExpiration: details.settings.enableDeadLetteringOnMessageExpiration, maxDeliveryCount: details.properties.maxDeliveryCount, enableBatchedOperations: details.settings.enableBatchedOperations, status: details.info.status, forwardTo: details.properties.forwardTo ?? "", forwardDeadLetteredMessagesTo: details.properties.forwardDeadLetteredMessagesTo ?? "", userMetadata: details.properties.userMetadata ?? "" }));
  const save = useMutation({ mutationFn: () => api.updateSubscription(connectionName, topicName, subscriptionName, clean(form)), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["subscription", connectionName, topicName, subscriptionName] }); queryClient.invalidateQueries({ queryKey: ["subscriptions", connectionName, topicName] }); } });
  return <form className="card settings-card" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div className="card-heading"><div><span className="eyebrow">Subscription</span><h2>Editable settings</h2></div><button className="button primary" disabled={save.isPending}><Save size={15} /> {save.isPending ? "Saving…" : "Save changes"}</button></div><div className="form-grid entity-form"><Field label="Lock duration" value={form.lockDuration} onChange={(value) => setForm({ ...form, lockDuration: value })} /><Field label="Default message TTL" value={form.defaultMessageTimeToLive} onChange={(value) => setForm({ ...form, defaultMessageTimeToLive: value })} /><Field label="Auto-delete on idle" value={form.autoDeleteOnIdle} onChange={(value) => setForm({ ...form, autoDeleteOnIdle: value })} /><Field label="Max delivery count" type="number" value={form.maxDeliveryCount} onChange={(value) => setForm({ ...form, maxDeliveryCount: Number(value) })} /><Field label="Forward to" value={form.forwardTo} onChange={(value) => setForm({ ...form, forwardTo: value })} /><Field label="Forward dead letters to" value={form.forwardDeadLetteredMessagesTo} onChange={(value) => setForm({ ...form, forwardDeadLetteredMessagesTo: value })} /><label><span>Status</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option>Active</option><option>Disabled</option><option>SendDisabled</option><option>ReceiveDisabled</option></select></label><label className="wide"><span>User metadata</span><textarea rows={4} value={form.userMetadata} onChange={(event) => setForm({ ...form, userMetadata: event.target.value })} /></label><div className="wide toggle-grid"><Toggle label="Batched operations" checked={form.enableBatchedOperations} onChange={(value) => setForm({ ...form, enableBatchedOperations: value })} /><Toggle label="Dead-letter expired messages" checked={form.deadLetteringOnMessageExpiration} onChange={(value) => setForm({ ...form, deadLetteringOnMessageExpiration: value })} /></div></div>{save.isSuccess && <div className="notice success">Subscription settings saved.</div>}{save.error && <div className="notice error">{save.error.message}</div>}</form>;
}

function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button className={`tab ${active ? "active" : ""}`} onClick={onClick}>{children}</button>; }
function Field({ label, value, type = "text", onChange }: { label: string; value: string | number; type?: string; onChange: (value: string) => void }) { return <label><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="toggle"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span>{label}</span></label>; }
function clean<T extends Record<string, unknown>>(value: T): T { return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, item === "" ? null : item])) as T; }
function formatRuleType(type: Rule["type"]) { return ({ Sql: "SQL", CorrelationId: "Correlation ID", TrueFilter: "Always true", FalseFilter: "Always false" } as const)[type]; }
function State({ title, detail, error = false }: { title: string; detail: string; error?: boolean }) { return <div className={`page-state ${error ? "error" : ""}`}><RefreshCw size={25} className={error ? "" : "spinning"} /><h2>{title}</h2><p>{detail}</p></div>; }
